/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2-MWebb
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTFsearch = new javax.swing.JTextField();
        BTNsubmit = new javax.swing.JButton();
        BTNsort = new javax.swing.JButton();
        BTNhistory = new javax.swing.JButton();
        BTNHome = new javax.swing.JButton();
        BTNlogout = new javax.swing.JButton();
        BTNexit = new javax.swing.JButton();
        LBLreview = new javax.swing.JLabel();
        BTNrefresh = new javax.swing.JButton();
        CBsubbedtabs = new javax.swing.JComboBox<>();
        BTNsubmitab = new javax.swing.JButton();
        LBLsuccess = new javax.swing.JLabel();
        BTNreject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTFsearch.setText("Search...");

        BTNsubmit.setText("Submit");
        BTNsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsubmitActionPerformed(evt);
            }
        });

        BTNsort.setText("Sort");
        BTNsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsortActionPerformed(evt);
            }
        });

        BTNhistory.setText("History");
        BTNhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNhistoryActionPerformed(evt);
            }
        });

        BTNHome.setText("Home");
        BTNHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHomeActionPerformed(evt);
            }
        });

        BTNlogout.setText("Logout");
        BTNlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlogoutActionPerformed(evt);
            }
        });

        BTNexit.setText("Exit");
        BTNexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNexitActionPerformed(evt);
            }
        });

        LBLreview.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LBLreview.setText("Review");

        BTNrefresh.setText("Refresh Tabs");

        CBsubbedtabs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tabs", "Tabname1", "Tabname2", "Tabbname3" }));

        BTNsubmitab.setText("Submit Tab");
        BTNsubmitab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsubmitabActionPerformed(evt);
            }
        });

        BTNreject.setText("Reject Tab");
        BTNreject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNrejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBsubbedtabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLreview)
                    .addComponent(BTNrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(TXTFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNsubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNsort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNhistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNlogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNexit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBLsuccess)
                        .addGap(18, 18, 18)
                        .addComponent(BTNreject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNsubmitab)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNsubmit)
                    .addComponent(BTNsort)
                    .addComponent(BTNhistory)
                    .addComponent(BTNHome)
                    .addComponent(BTNlogout)
                    .addComponent(BTNexit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBLreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CBsubbedtabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNsubmitab)
                    .addComponent(LBLsuccess)
                    .addComponent(BTNreject))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNexitActionPerformed

    private void BTNlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlogoutActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNlogoutActionPerformed

    private void BTNHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHomeActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNHomeActionPerformed

    private void BTNhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNhistoryActionPerformed
        new History().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNhistoryActionPerformed

    private void BTNsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsortActionPerformed
        new Sort().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNsortActionPerformed

    private void BTNsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsubmitActionPerformed
        new Submit().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNsubmitActionPerformed

    private void BTNsubmitabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsubmitabActionPerformed
        LBLsuccess.setText("Tab Submitted Successfully!");
        LBLsuccess.setVisible(true);
    }//GEN-LAST:event_BTNsubmitabActionPerformed

    private void BTNrejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNrejectActionPerformed
        LBLsuccess.setText("Tab rejected successfully");
        LBLsuccess.setVisible(true);
    }//GEN-LAST:event_BTNrejectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNHome;
    private javax.swing.JButton BTNexit;
    private javax.swing.JButton BTNhistory;
    private javax.swing.JButton BTNlogout;
    private javax.swing.JButton BTNrefresh;
    private javax.swing.JButton BTNreject;
    private javax.swing.JButton BTNsort;
    private javax.swing.JButton BTNsubmit;
    private javax.swing.JButton BTNsubmitab;
    private javax.swing.JComboBox<String> CBsubbedtabs;
    private javax.swing.JLabel LBLreview;
    private javax.swing.JLabel LBLsuccess;
    private javax.swing.JTextField TXTFsearch;
    // End of variables declaration//GEN-END:variables
}
