
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2-MWebb
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        BTNsubmit = new javax.swing.JButton();
        BTNsort = new javax.swing.JButton();
        BTNhistory = new javax.swing.JButton();
        BTNLogout = new javax.swing.JButton();
        BTNexit = new javax.swing.JButton();
        BTNadmin = new javax.swing.JButton();
        TXTFsearch = new javax.swing.JTextField();
        BTNtestDB = new javax.swing.JButton();
        LBLsuccess = new javax.swing.JLabel();
        BTNtesttab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        BTNsubmit.setBackground(new java.awt.Color(0, 0, 0));
        BTNsubmit.setForeground(new java.awt.Color(255, 255, 255));
        BTNsubmit.setText("Submit");
        BTNsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsubmitActionPerformed(evt);
            }
        });

        BTNsort.setBackground(new java.awt.Color(0, 0, 0));
        BTNsort.setForeground(new java.awt.Color(255, 255, 255));
        BTNsort.setText("Sort");
        BTNsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsortActionPerformed(evt);
            }
        });

        BTNhistory.setBackground(new java.awt.Color(0, 0, 0));
        BTNhistory.setForeground(new java.awt.Color(255, 255, 255));
        BTNhistory.setText("History");
        BTNhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNhistoryActionPerformed(evt);
            }
        });

        BTNLogout.setBackground(new java.awt.Color(0, 0, 0));
        BTNLogout.setForeground(new java.awt.Color(255, 255, 255));
        BTNLogout.setText("Log Out");
        BTNLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLogoutActionPerformed(evt);
            }
        });

        BTNexit.setBackground(new java.awt.Color(0, 0, 0));
        BTNexit.setForeground(new java.awt.Color(255, 255, 255));
        BTNexit.setText("Exit");
        BTNexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNexitActionPerformed(evt);
            }
        });

        BTNadmin.setBackground(new java.awt.Color(0, 0, 0));
        BTNadmin.setForeground(new java.awt.Color(255, 255, 255));
        BTNadmin.setText("Admin");
        BTNadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNadminActionPerformed(evt);
            }
        });

        TXTFsearch.setBackground(new java.awt.Color(0, 0, 0));
        TXTFsearch.setForeground(new java.awt.Color(255, 255, 255));
        TXTFsearch.setText("Search...");
        TXTFsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFsearchActionPerformed(evt);
            }
        });

        BTNtestDB.setText("TEST DB ");
        BTNtestDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtestDBActionPerformed(evt);
            }
        });

        BTNtesttab.setText("TEST TAB");
        BTNtesttab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtesttabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(TXTFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNsubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNsort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNhistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNadmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNexit)
                .addGap(4, 4, 4))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNtesttab)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(BTNtestDB))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(LBLsuccess))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNsubmit)
                    .addComponent(BTNsort)
                    .addComponent(BTNhistory)
                    .addComponent(BTNLogout)
                    .addComponent(BTNexit)
                    .addComponent(BTNadmin)
                    .addComponent(TXTFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(BTNtestDB)
                .addGap(18, 18, 18)
                .addComponent(LBLsuccess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNtesttab)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsortActionPerformed
        new Sort().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNsortActionPerformed

    private void BTNLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLogoutActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNLogoutActionPerformed

    private void BTNadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNadminActionPerformed
        new Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNadminActionPerformed

    private void BTNexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNexitActionPerformed

    private void TXTFsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFsearchActionPerformed

    private void BTNtestDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtestDBActionPerformed
        boolean connect = DAO.sqlTestDBConnection(); //calls query
        if (connect == true) {
            LBLsuccess.setText("Connection Made!");
        } else{
            LBLsuccess.setText("Connection Failed!");
        }
    }//GEN-LAST:event_BTNtestDBActionPerformed

    private void BTNsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsubmitActionPerformed
        new Submit().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNsubmitActionPerformed

    private void BTNhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNhistoryActionPerformed
        new History().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNhistoryActionPerformed

    private void BTNtesttabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtesttabActionPerformed
        
        new OpenTab().setVisible(true);
        this.dispose();
        
        
            
        
    }//GEN-LAST:event_BTNtesttabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLogout;
    private javax.swing.JButton BTNadmin;
    private javax.swing.JButton BTNexit;
    private javax.swing.JButton BTNhistory;
    private javax.swing.JButton BTNsort;
    private javax.swing.JButton BTNsubmit;
    private javax.swing.JButton BTNtestDB;
    private javax.swing.JButton BTNtesttab;
    private javax.swing.JLabel LBLsuccess;
    private javax.swing.JTextField TXTFsearch;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
