
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2-MWebb
 */
public class OpenTab extends javax.swing.JFrame {

    /**
     * Creates new form OpenTab
     */
    public OpenTab() {
        initComponents();
    }

    
    
    
            
        
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpenedTab = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Click for Tab!!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtOpenedTab.setEditable(false);
        txtOpenedTab.setColumns(20);
        txtOpenedTab.setRows(100);
        jScrollPane1.setViewportView(txtOpenedTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }

    
            private static final String CONN_URL = "jdbc:mysql://computing.gfmat.org:3306/";
             private static final String DB_NAME = "2022c_MWebb_test";
             private static final String USERNAME = "2022c_MWebb";
             private static final String PASSWORD = "4karqaUCSmddPKv8";
            
        public void sqlTestDBConnection() throws SQLException {
            System.out.println("test!");
            try {
                Connection con = DriverManager.getConnection(CONN_URL + DB_NAME, USERNAME, PASSWORD); 
                String query = "SELECT TabBody FROM Notes";
                ArrayList<String> list = new ArrayList<>();
                try (PreparedStatement preparedStatement = con.prepareStatement(query)){
                ResultSet resultSet = preparedStatement.executeQuery();
                ResultSetMetaData rsmd = resultSet.getMetaData();
                int columnCount = rsmd.getColumnCount();
                while(resultSet.next()){
                    int i = 1;
                    while(i<=columnCount){
                        list.add(resultSet.getString(i++));
                        txtOpenedTab.append(resultSet.getString("TabBody"));
                    }
                }
            }
                con.close();
                //System.out.println("cONNECTION MADE");
                //System.out.println(query);
                // Append text from the database to the text area
                //System.out.println(resultSet);
                    //txtOpenedTab.append(resultSet.getString("TabBody"));
                        
            } catch (Exception e) {
                        System.out.println("SOMETHING WENT WRONG..." + e.getMessage());
        }
            
        
            


            
       

        
    
        


    
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
            System.out.println("test");
            sqlTestDBConnection();
        } catch (SQLException ex) {
            Logger.getLogger(OpenTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOpenedTab;
    // End of variables declaration//GEN-END:variables

   
}
