/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2-MWebb
 */
public class Sort extends javax.swing.JFrame {

    /**
     * Creates new form Sort
     */
    public Sort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNhome = new javax.swing.JButton();
        BTNsubmit = new javax.swing.JButton();
        BTNhistory = new javax.swing.JButton();
        BTNAdmin = new javax.swing.JButton();
        BTNlogout = new javax.swing.JButton();
        BTNexit = new javax.swing.JButton();
        TXTFsearch = new javax.swing.JTextField();
        BTNmetal = new javax.swing.JButton();
        BTNrock = new javax.swing.JButton();
        BTNalt = new javax.swing.JButton();
        BTNpop = new javax.swing.JButton();
        BTNcountry = new javax.swing.JButton();
        BTNfolk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNhome.setBackground(new java.awt.Color(0, 0, 0));
        BTNhome.setForeground(new java.awt.Color(255, 255, 255));
        BTNhome.setText("Home");
        BTNhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNhomeActionPerformed(evt);
            }
        });

        BTNsubmit.setBackground(new java.awt.Color(0, 0, 0));
        BTNsubmit.setForeground(new java.awt.Color(255, 255, 255));
        BTNsubmit.setText("Submit");
        BTNsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsubmitActionPerformed(evt);
            }
        });

        BTNhistory.setBackground(new java.awt.Color(0, 0, 0));
        BTNhistory.setForeground(new java.awt.Color(255, 255, 255));
        BTNhistory.setText("History");
        BTNhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNhistoryActionPerformed(evt);
            }
        });

        BTNAdmin.setBackground(new java.awt.Color(0, 0, 0));
        BTNAdmin.setForeground(new java.awt.Color(255, 255, 255));
        BTNAdmin.setText("Admin");
        BTNAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAdminActionPerformed(evt);
            }
        });

        BTNlogout.setBackground(new java.awt.Color(0, 0, 0));
        BTNlogout.setForeground(new java.awt.Color(255, 255, 255));
        BTNlogout.setText("Log Out");
        BTNlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlogoutActionPerformed(evt);
            }
        });

        BTNexit.setBackground(new java.awt.Color(0, 0, 0));
        BTNexit.setForeground(new java.awt.Color(255, 255, 255));
        BTNexit.setText("Exit");
        BTNexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNexitActionPerformed(evt);
            }
        });

        TXTFsearch.setBackground(new java.awt.Color(0, 0, 0));
        TXTFsearch.setForeground(new java.awt.Color(255, 255, 255));
        TXTFsearch.setText("Search...");
        TXTFsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFsearchActionPerformed(evt);
            }
        });

        BTNmetal.setBackground(new java.awt.Color(255, 0, 0));
        BTNmetal.setForeground(new java.awt.Color(255, 255, 255));
        BTNmetal.setText("Metal");

        BTNrock.setBackground(new java.awt.Color(255, 204, 0));
        BTNrock.setForeground(new java.awt.Color(255, 255, 255));
        BTNrock.setText("Rock");
        BTNrock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNrockActionPerformed(evt);
            }
        });

        BTNalt.setBackground(new java.awt.Color(255, 255, 51));
        BTNalt.setForeground(new java.awt.Color(255, 255, 255));
        BTNalt.setText("Alternative");
        BTNalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNaltActionPerformed(evt);
            }
        });

        BTNpop.setBackground(new java.awt.Color(153, 255, 51));
        BTNpop.setForeground(new java.awt.Color(255, 255, 255));
        BTNpop.setText("Pop");
        BTNpop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpopActionPerformed(evt);
            }
        });

        BTNcountry.setBackground(new java.awt.Color(0, 204, 204));
        BTNcountry.setForeground(new java.awt.Color(255, 255, 255));
        BTNcountry.setText("Country");

        BTNfolk.setBackground(new java.awt.Color(0, 153, 255));
        BTNfolk.setForeground(new java.awt.Color(255, 255, 255));
        BTNfolk.setText("Folk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(BTNmetal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNrock, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNalt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TXTFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNhome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNsubmit)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BTNhistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNlogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNexit)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BTNpop, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(BTNfolk, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNhome)
                    .addComponent(BTNsubmit)
                    .addComponent(BTNhistory)
                    .addComponent(BTNAdmin)
                    .addComponent(BTNlogout)
                    .addComponent(BTNexit)
                    .addComponent(TXTFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTNmetal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTNrock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTNalt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BTNfolk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNcountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNpop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTFsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFsearchActionPerformed

    private void BTNsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsubmitActionPerformed
        new Submit().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNsubmitActionPerformed

    private void BTNpopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNpopActionPerformed

    private void BTNrockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNrockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNrockActionPerformed

    private void BTNaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNaltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNaltActionPerformed

    private void BTNlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlogoutActionPerformed
        new Login().setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_BTNlogoutActionPerformed

    private void BTNexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNexitActionPerformed
       this.dispose();
    }//GEN-LAST:event_BTNexitActionPerformed

    private void BTNhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNhomeActionPerformed
       new Home().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BTNhomeActionPerformed

    private void BTNhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNhistoryActionPerformed
        new History().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNhistoryActionPerformed

    private void BTNAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAdminActionPerformed
        new Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAdmin;
    private javax.swing.JButton BTNalt;
    private javax.swing.JButton BTNcountry;
    private javax.swing.JButton BTNexit;
    private javax.swing.JButton BTNfolk;
    private javax.swing.JButton BTNhistory;
    private javax.swing.JButton BTNhome;
    private javax.swing.JButton BTNlogout;
    private javax.swing.JButton BTNmetal;
    private javax.swing.JButton BTNpop;
    private javax.swing.JButton BTNrock;
    private javax.swing.JButton BTNsubmit;
    private javax.swing.JTextField TXTFsearch;
    // End of variables declaration//GEN-END:variables
}
