/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2-MWebb
 */
public class Submit extends javax.swing.JFrame {

    /**
     * Creates new form Submit
     */
    public Submit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTFsearch = new javax.swing.JTextField();
        BTNSort = new javax.swing.JButton();
        BTNhistory = new javax.swing.JButton();
        BTNAdmin = new javax.swing.JButton();
        BTNlogout = new javax.swing.JButton();
        BTNexit = new javax.swing.JButton();
        LBLreqinfo = new javax.swing.JLabel();
        LBLartist = new javax.swing.JLabel();
        LBLsongname = new javax.swing.JLabel();
        TXTFartist = new javax.swing.JTextField();
        TXTFsongname = new javax.swing.JTextField();
        CBpart = new javax.swing.JComboBox<>();
        LBLpart = new javax.swing.JLabel();
        LBLentertxt = new javax.swing.JLabel();
        TXTFtab = new javax.swing.JTextField();
        LBLerror1 = new javax.swing.JLabel();
        LBLerror2 = new javax.swing.JLabel();
        LBLgenre = new javax.swing.JLabel();
        BTNsubmittab = new javax.swing.JButton();
        TXTFgenre = new javax.swing.JTextField();
        TXTFtempo = new javax.swing.JTextField();
        LBLtempo = new javax.swing.JLabel();
        LBLerror3 = new javax.swing.JLabel();
        CBdiff = new javax.swing.JComboBox<>();
        LBLdiff = new javax.swing.JLabel();
        LBLerror4 = new javax.swing.JLabel();
        LBLerror5 = new javax.swing.JLabel();
        LBLsuccess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTFsearch.setText("Search....");

        BTNSort.setText("Sort");
        BTNSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSortActionPerformed(evt);
            }
        });

        BTNhistory.setText("History");
        BTNhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNhistoryActionPerformed(evt);
            }
        });

        BTNAdmin.setText("Admin");
        BTNAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAdminActionPerformed(evt);
            }
        });

        BTNlogout.setText("Log Out");
        BTNlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlogoutActionPerformed(evt);
            }
        });

        BTNexit.setText("Exit");
        BTNexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNexitActionPerformed(evt);
            }
        });

        LBLreqinfo.setText("Required Information");

        LBLartist.setText("Artist");

        LBLsongname.setText("Song Name");

        TXTFartist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFartistActionPerformed(evt);
            }
        });

        TXTFsongname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFsongnameActionPerformed(evt);
            }
        });

        CBpart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chorus", "Intro", "Verse 1", "Verse 2", "Verse 3", "Verse 4", "Bridge" }));

        LBLpart.setText("Part");

        LBLentertxt.setText("Enter Tab Text Here...");

        TXTFtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFtabActionPerformed(evt);
            }
        });

        LBLgenre.setText("Genre");

        BTNsubmittab.setText("Submit Tab");
        BTNsubmittab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsubmittabActionPerformed(evt);
            }
        });

        TXTFgenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFgenreActionPerformed(evt);
            }
        });

        LBLtempo.setText("Tempo");

        CBdiff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        LBLdiff.setText("Difficulty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLreqinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLentertxt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTFartist, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBLartist, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBLerror1))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TXTFsongname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LBLsongname))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBLpart)
                                            .addComponent(CBpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(LBLerror2)))
                            .addComponent(BTNsubmittab)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTFgenre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBLgenre)
                                    .addComponent(LBLerror4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TXTFtempo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LBLtempo))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBLdiff)
                                            .addComponent(CBdiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LBLsuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(LBLerror5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TXTFtab, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLerror3)))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNSort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNhistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNlogout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNexit)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSort)
                    .addComponent(BTNhistory)
                    .addComponent(BTNAdmin)
                    .addComponent(BTNlogout)
                    .addComponent(BTNexit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLreqinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLartist)
                    .addComponent(LBLsongname)
                    .addComponent(LBLpart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTFartist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTFsongname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLerror1)
                    .addComponent(LBLerror2))
                .addGap(2, 2, 2)
                .addComponent(LBLentertxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTFtab, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLerror3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLgenre)
                    .addComponent(LBLtempo)
                    .addComponent(LBLdiff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTFgenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTFtempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBdiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLerror4)
                    .addComponent(LBLerror5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNsubmittab)
                    .addComponent(LBLsuccess)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNhistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNhistoryActionPerformed

    private void BTNAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNAdminActionPerformed

    private void BTNlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlogoutActionPerformed
    new Login().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BTNlogoutActionPerformed

    private void BTNSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSortActionPerformed
    new Sort().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BTNSortActionPerformed

    private void BTNexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNexitActionPerformed
    this.dispose();
    }//GEN-LAST:event_BTNexitActionPerformed

    private void TXTFartistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFartistActionPerformed
    
    }//GEN-LAST:event_TXTFartistActionPerformed

    private void TXTFsongnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFsongnameActionPerformed
    
    }//GEN-LAST:event_TXTFsongnameActionPerformed

    private void TXTFtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFtabActionPerformed
    
    }//GEN-LAST:event_TXTFtabActionPerformed

    private void TXTFgenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFgenreActionPerformed
    
    }//GEN-LAST:event_TXTFgenreActionPerformed

    private void BTNsubmittabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsubmittabActionPerformed
    if (TXTFartist.getText().equals("")) {
        LBLerror1.setText("Artist cannot be blank!");
        LBLerror1.setVisible(true);
        
    }else if (TXTFsongname.getText().equals("")) {
        LBLerror2.setText("Song name cannot be blank!");
        LBLerror2.setVisible(true);
        
    }else if (TXTFtab.getText().equals("")) {
        LBLerror3.setText("Tab field cannot be empty!");
        LBLerror3.setVisible(true);
        
    }else if (TXTFgenre.getText().equals("")) {
        LBLerror4.setText("Genre cannot be blank!");
        LBLerror4.setVisible(true);
        
    }else if (TXTFtempo.getText().equals("")) {
        LBLerror5.setText("Tempo cannot be blank!");
        LBLerror5.setVisible(true);
    }else{ 
        LBLsuccess.setText("Tab submitted successfully");
        LBLsuccess.setVisible(true);
    }
    }//GEN-LAST:event_BTNsubmittabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAdmin;
    private javax.swing.JButton BTNSort;
    private javax.swing.JButton BTNexit;
    private javax.swing.JButton BTNhistory;
    private javax.swing.JButton BTNlogout;
    private javax.swing.JButton BTNsubmittab;
    private javax.swing.JComboBox<String> CBdiff;
    private javax.swing.JComboBox<String> CBpart;
    private javax.swing.JLabel LBLartist;
    private javax.swing.JLabel LBLdiff;
    private javax.swing.JLabel LBLentertxt;
    private javax.swing.JLabel LBLerror1;
    private javax.swing.JLabel LBLerror2;
    private javax.swing.JLabel LBLerror3;
    private javax.swing.JLabel LBLerror4;
    private javax.swing.JLabel LBLerror5;
    private javax.swing.JLabel LBLgenre;
    private javax.swing.JLabel LBLpart;
    private javax.swing.JLabel LBLreqinfo;
    private javax.swing.JLabel LBLsongname;
    private javax.swing.JLabel LBLsuccess;
    private javax.swing.JLabel LBLtempo;
    private javax.swing.JTextField TXTFartist;
    private javax.swing.JTextField TXTFgenre;
    private javax.swing.JTextField TXTFsearch;
    private javax.swing.JTextField TXTFsongname;
    private javax.swing.JTextField TXTFtab;
    private javax.swing.JTextField TXTFtempo;
    // End of variables declaration//GEN-END:variables
}
